### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by johndougherty68** [johndougherty68/TripwireService#4]
It also stopped alerting if changes are made to the bait file. The Tripwire log file was not updated. Event log shows:

Log Name:      Application
Source:        Service1
Date:          4/22/2016 10:48:54 AM
Event ID:      0
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      nwk-test.IFIC.local
Description:
Failed to stop service. System.UnauthorizedAccessException: Access to the path '###_#.doc' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileInfo.Delete()
   at CryptoWatcher.CryptoWatcher.DeleteTemps()
   at CryptoWatcher.CryptoWatcher.Stop()
   at CryptoWatcherService.CryptoWatcherService.OnStop()
   at System.ServiceProcess.ServiceBase.DeferredStop()
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Service1" />
    <EventID Qualifiers="0">0</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2016-04-22T14:48:54.000000000Z" />
    <EventRecordID>174014</EventRecordID>
    <Channel>Application</Channel>
    <Computer>nwk-test.IFIC.local</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Failed to stop service. System.UnauthorizedAccessException: Access to the path '###_#.doc' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileInfo.Delete()
   at CryptoWatcher.CryptoWatcher.DeleteTemps()
   at CryptoWatcher.CryptoWatcher.Stop()
   at CryptoWatcherService.CryptoWatcherService.OnStop()
   at System.ServiceProcess.ServiceBase.DeferredStop()</Data>
  </EventData>
</Event>

**Comment by johndougherty68** [comment]
![error1](https://cloud.githubusercontent.com/assets/6403669/14745910/46955748-087b-11e6-8cc4-85c33e4f2497.png)

**Comment by johndougherty68** [comment]
This seems to be caused by an Explorer window being open in a bait folder. Please close any window which is in a bait folder before stopping the service. Alternately, the service will stop and you will have to delete the folder you are in.
